nginx:
  build: ./nginx

app1:
  build: ./app
  ports:
    - "3000"
  links:
    - "cache:redis"

app2:
  build: ./app
  ports:
    - "3000"
  links:
    - "cache:redis"

app3:
  build: ./app
  ports:
    - "3000"
  links:
    - "cache:redis"

cache:
  image: redis